#!/usr/bin/python

REPLY = """Content-type: text/html

<html><title>Languages2</title>
<body>
<h1>Hello World Selector</h1>
<p>Similar to file <a href='../languages.html'>languages.html</a>, but this page is
dynamically generated by a Python CGI script, using
selection list and input field names imported from a common Python
module on the server. Only the common module must be maintained as
new languages are added, because it is shared with the reply script.

To see the code that generates this page and the reply, click
<a href='getfile.py?filename=cgi-bin/languages2.py'>here</a>
<a href='getfile.py?filename=cgi-bin/languages2reply.py'>here</a>
<a href='getfile.py?filename=cgi-bin/languages2common.py'>here</a>, and
<a href='getfile.py?filename=cgi-bin/formMockup.py'>here</a>.</p>
<hr>
<form method='post' action='languages2reply.py'>
<p><b>Select a programming laguage:</b></p>
    <p><select name=%s>
        <option>All
        %s
        <option>Other
    </select></p>
    <p><input type=Submit>
</form>
</body></html>
"""

from languages2common import hellos, inputkey

options = []
for lang in hellos:
    options.append('<option>' + lang)
options = '\n\t\t'.join(options)
print(REPLY % (inputkey, options))
